### ISSUE TITLE
is this a production ready?

### ISSUE THREAD

**Issue by tws0002** [cgwire/cgwire#10]
Hi,

because I'm using window!! so I think docker cgwire is the best way for me to start. 
the only question is can we use this for production?

Thanks 
Desmond

**Comment by frankrousseau** [comment]
I think you can use it with volumes. At least your data won't be lost. 
We have no user who uses the Docker installation, but we would be glad to help you if you meet any bugs. That would be the opportunity to make it suitable for anyone.

**Comment by tws0002** [comment]
Hey, Frank thanks for the quick reply. 
I'm very new to docker!! can you explain more about volumes that u mention?

**Comment by frankrousseau** [comment]
With a Docker container there is no real persistence, every infornation is wiped out when the container is removed. That's why they added the concept of volume. Once you declare a volume, a link between a folder of the container and folder of the host, you can persist data in a traditional way.

That command uses container: 

```
docker run -ti --rm -p 80:80 --name cgwire -v zou-storage:/var/lib/postgresql -v zou-storage:/opt/zou/zou/thumbnails cgwire
```

**Comment by frankrousseau** [comment]
Sorry for my answer in this issue. You should not use the Docker image in production. We cannot ensure its accountability.

**Comment by nledez** [comment]
To complete the answer, this image is made to help in the evaluation of Kitsu.
And they do not provide the:
- Docker best practices (one container per process).
- A docker-compose to help the separation of different images/containers
- The management of volumes

**Comment by juangea** [comment]
I'm not sure how can those three points affect the work of Kitsu, could be interesting to know.

So far I'm using it and it has a very good looking aspect, and there is no other way to run kitsu on a Mac server AFAIK, specially with the M1, that's why we use it in production

**Comment by frankrousseau** [comment]
You should have a look at this Docker compose maintained by the community: https://gitlab.com/mathbou/docker-cgwire/
