### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mottosso** [cgwire/cgwire#11]
Hi @frankrousseau,

Would it be possible to add versions to the Docker images? At the moment, there exists only `:latest` which makes it tricky to guarantee a particular state for anything depending on this image.

Preferably, there would exist something akin to:

```bash
$ docker run cgwire/cgwire:0.6
```

Such that I know what to expect when pulling this image, that it cannot change its behavior without my knowledge and that when I upgrade it is known and explicit.

**Comment by frankrousseau** [comment]
You're right it's something I have to fix. I don't know how to do that but it's probably easy to handle.

**Comment by mottosso** [comment]
If you're pushing manually, you can "tag" an image. Either after you've built it, or during.

```bash
# During build
$ docker build -t cgwire/cgwire:0.6.10 .

# After build
$ docker tag cgwire/cgwire cgwire/cgwire:0.6.10
```

And then push as per usual.

```bash
$ docker push cgwire/cgwire:0.6.10
```

**Comment by mottosso** [comment]
Ah, that's a good idea. What you can do is have a branch per version, and then make a tag per branch via Docker Hub.

Here's an example of how I've done that for one my images.

- https://github.com/mottosso/docker-maya
- https://hub.docker.com/r/mottosso/maya/tags/

Alternatively, you can not use Hub, and push images yourself via Travis. For example..

- https://github.com/getavalon/docker/blob/3e4cb6096dba8f8d11d28ddbbe70219aa4866800/.travis.yml#L50

**Comment by frankrousseau** [comment]
Sorry for the long delay but it's now fixed. Pushing generates a latest image. Adding a tag generates a tagged image too. It will allow to mark stable releases.
Thank you for your help with the suggestion and the code snippets.
