### ISSUE TITLE
Postgresql failed on start

### ISSUE THREAD

**Issue by PiloeGAO** [cgwire/cgwire#16]
Hello,

I tried several times to install the docker container (PopOS 20.04 LTS), kitsu gui worked as expected but I cant login with the mail/password given.

After some research, I discovered that the DB wasn't working.
![image](https://user-images.githubusercontent.com/43547972/87959231-ded96500-cab2-11ea-8ddf-c09bab8ca098.png)

You can find here the Docker's log:

> admin@pop-os:~/docker-cgwire/cgwire$ sudo docker run -ti --rm -p 80:80 --name cgwire -v zou-storage:/var/lib/postgresql -v zou-storage:/opt/zou/previews cgwire/cgwire
> Running Zou...
> 2020-07-20 15:46:25,259 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> 2020-07-20 15:46:25,262 INFO RPC interface 'supervisor' initialized
> 2020-07-20 15:46:25,262 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2020-07-20 15:46:25,263 INFO supervisord started with pid 10
> 2020-07-20 15:46:26,264 INFO spawned: 'gunicorn' with pid 13
> 2020-07-20 15:46:26,265 INFO spawned: 'gunicorn-events' with pid 14
> 2020-07-20 15:46:26,268 INFO spawned: 'redis' with pid 15
> 2020-07-20 15:46:26,269 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES
> 2020-07-20 15:46:26,270 INFO spawned: 'nginx' with pid 16
> 2020-07-20 15:46:27,288 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-20 15:46:27,288 INFO success: gunicorn-events entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-20 15:46:27,288 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-20 15:46:27,289 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES
> 2020-07-20 15:46:27,289 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2020-07-20 15:46:29,321 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES
> 2020-07-20 15:46:32,335 INFO spawnerr: unknown error making dispatchers for 'postgresql': EACCES
> 2020-07-20 15:46:32,335 INFO gave up: postgresql entered FATAL state, too many start retries too quickly
> ^C2020-07-20 15:52:50,200 WARN received SIGINT indicating exit request
> 2020-07-20 15:52:50,200 INFO waiting for redis, gunicorn, gunicorn-events, nginx to die
> 2020-07-20 15:52:50,203 INFO stopped: nginx (exit status 0)
> ^C2020-07-20 15:52:50,888 WARN received SIGINT indicating exit request
> 2020-07-20 15:52:51,119 INFO stopped: redis (exit status 0)
> 2020-07-20 15:52:52,351 INFO stopped: gunicorn (exit status 0)
> 2020-07-20 15:52:52,353 INFO stopped: gunicorn-events (exit status 0)

Thank you

**Comment by frankrousseau** [comment]
Hello, are you trying to update an existing installation?

Everything seems fine with the continuous integration: https://travis-ci.org/github/cgwire/cgwire

**Comment by PiloeGAO** [comment]
Hello, 
It's a new installation on a scratch Ubuntu 20.04 machine with only docker installed.
I tried 4 times, 2 on Virtual Box VM and 2 on real server.

**Comment by vltmedia** [comment]
The docker build isn't working, Postgres still fails.

**Comment by frankrousseau** [comment]
I was able to reproduce the problem on the CI: https://travis-ci.org/github/cgwire/cgwire
