### ISSUE TITLE
Req: Update docker version to current

### ISSUE THREAD

**Issue by ddesmond** [cgwire/cgwire#22]
When you have time, please, can you update docker to latest current kitsu versions?
thanks!

🚀 🎸 🍰

**Comment by pilou-** [comment]
The docker image has been [updated](https://hub.docker.com/layers/cgwire/cgwire/latest/images/sha256-8dd8441325ee934d7ca33083d737b5ec8d8df4d767c76c42cdb57c12aab8102c).

**Comment by frankrousseau** [comment]
Yep, it's done!

**Comment by ddesmond** [comment]
you guys are awesome. owning 9 beers now! ;)
